apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  type: NodePort
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: 8002-tcp
      port: 8002
      targetPort: 8002
  selector:
    app: api
