apiVersion: v1
kind: Pod
metadata:
  name: web-products
  labels:
    tier: front
    release : stable
spec:
  containers:
    - name:  redis-service:
      image: bitnami/redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
      volumeMounts:
        - name: data
          mountPath: /data
      env:
         ALLOW_EMPTY_PASSWORD: "yes"

    - name: mongo
      image: mongo
      volumeMounts:
        - name: data
          mountPath: /data
      env:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    - name: frontend
    image: ramondomiingos/front-products
    ports:
      - containerPort: 8002
        protocol: TCP
    env:
      VITE_URL_PRODUCTS: http://api:8001
    
    - name: api
      image: ramondomiingos/api-products
      ports:
        - containerPort: 8001
          protocol: TCP
      env:
        PORT": 8001 
        REDIS_URL: redis-service
        REDIS_PORT: 6379
        REDIS_EXPIRE: 10
        MONGO_USERNAME: root
        MONGO_PASSWORD: example
        MONGO_URL"mongo: 27017
        MONGO_DB: product

  volumes:
    - name: data
      emptyDir: {}